# Generated by Django 3.2 on 2021-04-20 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('page_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_name', models.CharField(max_length=255)),
                ('content_text', models.TextField(blank=True)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('moderation_date', models.DateField(auto_now=True)),
                ('visibility', models.BooleanField(default=True)),
                ('page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='artinox_spb_app.pagename')),
            ],
            options={
                'verbose_name': 'Контент страниц',
                'verbose_name_plural': 'Контент страниц',
            },
        ),
    ]
