# Generated by Django 3.2 on 2021-04-16 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('block_name', models.CharField(max_length=255)),
                ('content_text', models.TextField(blank=True)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('moderation_date', models.DateField(auto_now=True)),
                ('visibility', models.BooleanField(default=True)),
            ],
        ),
    ]
