# Generated by Django 3.2 on 2021-05-06 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artinox_spb_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagecontent',
            name='photo',
            field=models.ImageField(null=True, upload_to='photos/<django.db.models.query_utils.DeferredAttribute object at 0x00000201808D99A0>', verbose_name='путь до фото'),
        ),
    ]
