# Generated by Django 3.2 on 2021-04-24 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artinox_spb_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagename',
            options={'ordering': ['id'], 'verbose_name': 'Страницы', 'verbose_name_plural': 'Страницы'},
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='block_name',
            field=models.CharField(max_length=255, verbose_name='название блока'),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='content_text',
            field=models.TextField(blank=True, verbose_name='содержимое блока'),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='creation_date',
            field=models.DateField(auto_now_add=True, verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='moderation_date',
            field=models.DateField(auto_now=True, verbose_name='дата редактирования'),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='visibility',
            field=models.BooleanField(default=True, verbose_name='видимость'),
        ),
        migrations.AlterField(
            model_name='pagename',
            name='page_name',
            field=models.CharField(max_length=255, verbose_name='название страницы'),
        ),
        migrations.AlterField(
            model_name='pagename',
            name='title',
            field=models.CharField(db_index=True, max_length=255, verbose_name='заголовок'),
        ),
    ]
