# Generated by Django 3.2 on 2021-04-24 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artinox_spb_app', '0002_auto_20210425_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagecontent',
            name='photo',
            field=models.ImageField(null=True, upload_to='photos/<django.db.models.query_utils.DeferredAttribute object at 0x00000190CBE679D0>', verbose_name='путь до фото'),
        ),
    ]
