# Generated by Django 3.2 on 2021-05-09 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artinox_spb_app', '0002_alter_pagecontent_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagecontent',
            name='photo',
            field=models.ImageField(null=True, upload_to='photos/<django.db.models.query_utils.DeferredAttribute object at 0x000001DBA1179970>', verbose_name='путь до фото'),
        ),
    ]
