# Generated by Django 3.2 on 2021-04-24 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artinox_spb_app', '0003_pagecontent_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagecontent',
            name='content_text',
            field=models.TextField(blank=True, null=True, verbose_name='содержимое блока'),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='photo',
            field=models.ImageField(null=True, upload_to='photos/<django.db.models.query_utils.DeferredAttribute object at 0x00000154272479A0>', verbose_name='путь до фото'),
        ),
    ]
