# Generated by Django 3.2 on 2021-04-25 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artinox_spb_app', '0005_auto_20210425_0204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagename',
            name='page',
        ),
        migrations.AddField(
            model_name='pagecontent',
            name='page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='artinox_spb_app.pagename'),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='photo',
            field=models.ImageField(null=True, upload_to='photos/<django.db.models.query_utils.DeferredAttribute object at 0x0000024AE90E79A0>', verbose_name='путь до фото'),
        ),
    ]
