# Generated by Django 3.2 on 2021-04-25 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artinox_spb_app', '0006_auto_20210425_0331'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PageName',
            new_name='PageInfo',
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='photo',
            field=models.ImageField(null=True, upload_to='photos/<django.db.models.query_utils.DeferredAttribute object at 0x00000144B24679D0>', verbose_name='путь до фото'),
        ),
    ]
